# Generated by Django 4.0 on 2024-02-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataMonitored',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('coordinate', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_check', models.DateTimeField(auto_now_add=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('analysis_made', models.JSONField()),
                ('state', models.CharField(choices=[('Processing', 'Processing'), ('Error', 'Error'), ('Success', 'Success')], default='Processing', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.user')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NDVI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NDWI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SDVI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NDBI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SAVI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MSAVI2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EVI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MNDWI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeforestMeasure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LMI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='monitoring.datamonitored')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.user')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monitoring.user')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.analysis')),
            ],
        ),
    ]
